import type { Metadata } from "next";
import { Readex_Pro, Roboto } from "next/font/google";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-roboto",
});
const readexPro = Readex_Pro({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-read-ex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-[#fb9202] to-[#ff4500]  ">
        {children}
      </body>
    </html>
  );
}
